cd /work/scratch-pw2/ptg21/u-cq330/netcdf_OPT/

ncrename -O -v mass_fraction_of_o3_in_air,mole_fraction_of_o3_in_air ANTHRO_TROPICS_CONSTANT_o3_vmr_1995_2015.nc ANTHRO_TROPICS_CONSTANT_o3_vmr_1995_2015.nc
ncatted -O -a units,mole_fraction_of_o3_in_air,m,c,"mol mol-1" ANTHRO_TROPICS_CONSTANT_o3_vmr_1995_2015.nc ANTHRO_TROPICS_CONSTANT_o3_vmr_1995_2015.nc
ncatted -O -a standard_name,mole_fraction_of_o3_in_air,m,c,"mole_fraction_of_o3_in_air" ANTHRO_TROPICS_CONSTANT_o3_vmr_1995_2015.nc ANTHRO_TROPICS_CONSTANT_o3_vmr_1995_2015.nc

ncrename -O -v mass_fraction_of_isoprene_in_air,mole_fraction_of_isoprene_in_air ANTHRO_TROPICS_CONSTANT_c5h8_vmr_1995_2015.nc ANTHRO_TROPICS_CONSTANT_c5h8_vmr_1995_2015.nc
ncatted -O -a units,mole_fraction_of_isoprene_in_air,m,c,"mol mol-1" ANTHRO_TROPICS_CONSTANT_c5h8_vmr_1995_2015.nc ANTHRO_TROPICS_CONSTANT_c5h8_vmr_1995_2015.nc
ncatted -O -a standard_name,mole_fraction_of_isoprene_in_air,m,c,"mole_fraction_of_isoprene_in_air" ANTHRO_TROPICS_CONSTANT_c5h8_vmr_1995_2015.nc ANTHRO_TROPICS_CONSTANT_c5h8_vmr_1995_2015.nc

ncrename -O -v mass_fraction_of_methane_in_air,mole_fraction_of_methane_in_air ANTHRO_TROPICS_CONSTANT_ch4_vmr_1995_2015.nc ANTHRO_TROPICS_CONSTANT_ch4_vmr_1995_2015.nc
ncatted -O -a units,mole_fraction_of_methane_in_air,m,c,"mol mol-1" ANTHRO_TROPICS_CONSTANT_ch4_vmr_1995_2015.nc ANTHRO_TROPICS_CONSTANT_ch4_vmr_1995_2015.nc
ncatted -O -a standard_name,mole_fraction_of_methane_in_air,m,c,"mole_fraction_of_methane_in_air" ANTHRO_TROPICS_CONSTANT_ch4_vmr_1995_2015.nc ANTHRO_TROPICS_CONSTANT_ch4_vmr_1995_2015.nc

ncrename -O -v mass_fraction_of_carbon_monoxide_in_air,mole_fraction_of_carbon_monoxide_in_air ANTHRO_TROPICS_CONSTANT_co_vmr_1995_2015.nc ANTHRO_TROPICS_CONSTANT_co_vmr_1995_2015.nc
ncatted -O -a units,mole_fraction_of_carbon_monoxide_in_air,m,c,"mol mol-1" ANTHRO_TROPICS_CONSTANT_co_vmr_1995_2015.nc ANTHRO_TROPICS_CONSTANT_co_vmr_1995_2015.nc
ncatted -O -a standard_name,mole_fraction_of_carbon_monoxide_in_air,m,c,"mole_fraction_of_carbon_monoxide_in_air" ANTHRO_TROPICS_CONSTANT_co_vmr_1995_2015.nc ANTHRO_TROPICS_CONSTANT_co_vmr_1995_2015.nc

ncrename -O -v mass_fraction_of_formaldehyde_in_air,mole_fraction_of_formaldehyde_in_air ANTHRO_TROPICS_CONSTANT_hcho_vmr_1995_2015.nc ANTHRO_TROPICS_CONSTANT_hcho_vmr_1995_2015.nc
ncatted -O -a units,mole_fraction_of_formaldehyde_in_air,m,c,"mol mol-1" ANTHRO_TROPICS_CONSTANT_hcho_vmr_1995_2015.nc ANTHRO_TROPICS_CONSTANT_hcho_vmr_1995_2015.nc
ncatted -O -a standard_name,mole_fraction_of_formaldehyde_in_air,m,c,"mole_fraction_of_formaldehyde_in_air" ANTHRO_TROPICS_CONSTANT_hcho_vmr_1995_2015.nc ANTHRO_TROPICS_CONSTANT_hcho_vmr_1995_2015.nc

ncrename -O -v mass_fraction_of_nitrogen_dioxide_in_air,mole_fraction_of_nitrogen_dioxide_in_air ANTHRO_TROPICS_CONSTANT_no2_vmr_1995_2015.nc ANTHRO_TROPICS_CONSTANT_no2_vmr_1995_2015.nc
ncatted -O -a units,mole_fraction_of_nitrogen_dioxide_in_air,m,c,"mol mol-1" ANTHRO_TROPICS_CONSTANT_no2_vmr_1995_2015.nc ANTHRO_TROPICS_CONSTANT_no2_vmr_1995_2015.nc
ncatted -O -a standard_name,mole_fraction_of_nitrogen_dioxide_in_air,m,c,"mole_fraction_of_nitrogen_dioxide_in_air" ANTHRO_TROPICS_CONSTANT_no2_vmr_1995_2015.nc ANTHRO_TROPICS_CONSTANT_no2_vmr_1995_2015.nc

ncrename -O -v mass_fraction_of_nitrogen_monoxide_in_air,mole_fraction_of_nitrogen_monoxide_in_air ANTHRO_TROPICS_CONSTANT_no_vmr_1995_2015.nc ANTHRO_TROPICS_CONSTANT_no_vmr_1995_2015.nc
ncatted -O -a units,mole_fraction_of_nitrogen_monoxide_in_air,m,c,"mol mol-1" ANTHRO_TROPICS_CONSTANT_no_vmr_1995_2015.nc ANTHRO_TROPICS_CONSTANT_no_vmr_1995_2015.nc
ncatted -O -a standard_name,mole_fraction_of_nitrogen_monoxide_in_air,m,c,"mole_fraction_of_nitrogen_monoxide_in_air" ANTHRO_TROPICS_CONSTANT_no_vmr_1995_2015.nc ANTHRO_TROPICS_CONSTANT_no_vmr_1995_2015.nc

ncrename -O -v mass_fraction_of_hydroxyl_radical_in_air,mole_fraction_of_hydroxyl_radical_in_air ANTHRO_TROPICS_CONSTANT_oh_vmr_1995_2015.nc ANTHRO_TROPICS_CONSTANT_oh_vmr_1995_2015.nc
ncatted -O -a units,mole_fraction_of_hydroxyl_radical_in_air,m,c,"mol mol-1" ANTHRO_TROPICS_CONSTANT_oh_vmr_1995_2015.nc ANTHRO_TROPICS_CONSTANT_oh_vmr_1995_2015.nc
ncatted -O -a standard_name,mole_fraction_of_hydroxyl_radical_in_air,m,c,"mole_fraction_of_hydryoxyl_radical_in_air" ANTHRO_TROPICS_CONSTANT_oh_vmr_1995_2015.nc ANTHRO_TROPICS_CONSTANT_oh_vmr_1995_2015.nc
